# Generated by Django 3.2.9 on 2022-04-20 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0010_alter_post_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='comment',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
    ]
